libp2p/rust-yamux

src/connection.rs
If no stream that corresponds to a new stream ID can be found, continue with the next ID. The stream might have been reset in the meantime.
=> Loop over new stream IDs.

src/connection.rs
Addresses https://github.com/libp2p/rust-libp2p/issues/346.
Includes changes from https://github.com/paritytech/yamux/pull/8. If merged, https://github.com/paritytech/yamux/pull/9 can be closed.
Future work may change this such that the underlying resource is also dropped on error.
=> Destroy on error

.travis.yml
Before merging, Travis needs to be enabled for this repo.
Related to #11.
=> Add basic travis config.

src/connection.rs, src/stream.rs
The spec states, that for Ping (and GoAway) frames 0 should be used as stream ID, so we better respond.
=> Handle stream ID 0 in Ping frames.

src/connection.rs, src/frame/header.rs
Rename the existing `shutdown` method to `close` and make the latter flush any buffered data before closing. The new `shutdown` behaviour is merely adding a GO_AWAY frame to the pending data which is sent out on `flush` or `close`.
=> Send GO_AWAY frame on shutdown.

src/connection.rs
Currently the (private) `Inner` type is `Debug` but not the public type.
=> Add Debug impl for Connection

src/connection.rs
`Stream::poll()` takes a `&mut self` which is problematic as libp2p's `StreamMuxer`s methods take immutable references. This was previously worked around in libp2p by wrapping `yamux::Connection` in an extra `Mutex`. This PR implements `poll()` as an inherent method that takes `&self` making it possible to call without a mutex from `libp2p`.
The PR retains the `Stream` impl so that code can use its convenient API.
=> Add inherent poll() to Connection

src/connection.rs
`reset()` already [removes the stream](https://github.com/paritytech/yamux/pull/28/files#diff-c80c453b374ae714374e0f9d9d86ba1cL484).
=> Don't attempt to remove a stream twice

src/connection.rs
Except for `open_stream` always create a `StreamEntry` with a receive window = DEFAULT_CREDIT. The remote has to assume we use the default. If we configured a receive window size greater than that and use that right away we will wait for more data while the remote is waiting for our window update. The end result is a deadlock.
This commit instantiates a `StreamEntry` in `on_data` and `on_window_update` with a default receive window, matching the expectation from remote and only when sending window updates will we use the configured receive window size. The simple rule is: Only change the receive window size after telling the other end about it.
=> Fix handling of receive window.

src/connection.rs
Currently, if `poll_flush_notify` returns `NotReady` in `flush_pending` after we managed to start sending our pending data we will not attempt to resume flushing until more pending data has been accumulated which does not necessarily happen.
Instead, we must attempt to flush unconditionally in `process_incoming` to ensure any pending flush operation completes.
=> Always attempt to flush data in `process_incoming`.

src/chunks.rs, src/connection.rs, src/frame/codec.rs, src/frame/mod.rs, src/lib.rs, src/stream.rs
Instead of copying bytes from incoming data frame bodies into the stream buffer just move the bodies into a queue of `BytesMut` values.
=> Avoid unnecessary copying of data frame bodies.

src/connection.rs
Check the stream state in `Connection::reset`. If `Closed` it means that either the connection is dead, or a reset frame has already been received for this stream, hence it is not necessary to send out a new one.
On top of #36.
=> No redundant reset

Cargo.toml, src/frame/codec.rs, src/lib.rs, tests/smoke.rs
Includes:
* Using OS-assigned, free port numbers.
* Randomising test inputs.
* Extracting reusable functionality.
* Begin extending integration test coverage, e.g. for  https://github.com/paritytech/yamux/pull/36. More tests may follow.
Thereby upgrade the `quickcheck` dependency.
=> Randomise and expand integration tests.

src/connection.rs
Also remove `Connection::shutdown` and fold its behaviour into `Connection::close`, i.e. the close will append a graceful `GoAway` frame to the buffer before proceeding to close the connection.
The new `ConnStatus` enum has three states, `Open`, `Shutdown` and `Closed`. Most places continue to distinguish only between `Open` and not open. `Shutdown` is set by `close` in case it can not complete the close but is notified again. Besides calling `close` again, only flushing the connection is possible in `Shtudown` mode.
=> Replace status boolean with `ConnStatus` enum.

src/connection.rs, src/lib.rs
By default streams are able to read data from their local buffer even after the connection has been closed. Setting `read_after_close` to false prevents this and causes stream reads to return `Ok(0)` as soon as the connection has been closed.
=> Add `read_after_close` setting.

src/connection.rs
`read_after_close` is not relevant here. If the connection is not open we should not attempt to read from it anymore once the buffer has been exhausted, regardless of this setting.
=> Fix logic error related to `read_after_close`.

tests/concurrent.rs
This creates a lot of streams over a single connection, each sending and receiving one data item. Note that this test does sometimes not terminate which indicates a bug in this crate.
=> Add another test.

src/connection.rs, src/error.rs, src/lib.rs, tests/concurrent.rs
The cause for the sometimes not terminating test was that both endpoints
attempt to finish a writing operation and would not continue reading
from the socket. We must--as much as possible--continue reading, even
when we can not complete a write operation to prevent deadlock.
Since we buffer pending frames, which are meant to be delivered to the
remote and we make progress even if we can not write, we must limit the
resource growth of the pending frames buffer. This PR adds a new setting
`max_pending_frames` to do just that.
=> Limit pending buffer and fix test.

src/connection.rs
This is based on a former branch from @twittner that adds some benchmarks which used to stall on the current implementation. This PR is mostly for historical and informational purposes as the new implementation will supersede it shortly. The problem was diagnosed as the following:
If `poll_stream_notify`, `start_send_notify` or `poll_flush_notify` on a `Spawn` are called prior to registering the current task with `self.tasks`, a notification may be missed. I.e. `self.tasks` may be notified *before* the `NotReady` result is returned, making it unsafe to insert the current task only upon receiving `NotReady` from these functions.
This was observed in stalling benchmarks with concurrent streams. In particular, if these benchmarks stalled, they always stalled on receiving the last frame of …
=> Fix missed task notifications.

src/connection.rs
I checked all the execution paths on the intermediate code from your repository for double lock.
I found one path that may trigger a double lock.
https://github.com/paritytech/yamux/blob/6dd0a5affdd07c4602b2f004836e5a5dacfad165/src/connection.rs#L143-L162
The first lock happens on [L144](https://github.com/paritytech/yamux/blob/6dd0a5affdd07c4602b2f004836e5a5dacfad165/src/connection.rs#L144). Then on [L156](https://github.com/paritytech/yamux/blob/6dd0a5affdd07c4602b2f004836e5a5dacfad165/src/connection.rs#L156), a stream is created from a cloned self connection, which in fact clones the inner Arc. Now the stream holds a ptr to the Inner of connection!
https://github.com/paritytech/yamux/blob/master/src/connection.rs#L62
If any panic happens on …
=> Comment to warn future developers a double lock when unwinding

Cargo.toml, benches/concurrent.rs, src/connection.rs, src/frame.rs, src/frame/header.rs, src/frame/io.rs, tests/concurrent.rs, tests/smoke.rs
Updates from `futures-preview 0.3.0-alpha.19` to `futures-0.3.1` with the following changes:
- Remove `futures_codec` dependency.
- Replace `header::Codec` with `header::{encode, decode}` functions.
- Add `frame::io` module which contains the `Io` type which decodes
frames, implements `futures::stream::Stream` and also allows writing
frames (buffered) to the socket.
- Remove the `tokio` benchmarks as they are very similar to the
`async-std` ones which allows us to remove one (dev) dependency.
While `Io::send` does not perform an immediate flush we nevertheless flush frequently and leave it for another PR to optimise this aspect.
=> Update to futures-0.3

src/connection.rs, src/connection/stream.rs, src/lib.rs, src/tests.rs
Keep the public API surface minimal. We may at some point replace the `Mutex` around `Shared` with a futures-aware lock at which point `Stream::state` would no longer be a synchronous method. As the method is not used externally yet it is best not to introduce it at this point. Since we nevertheless use this in our tests, `smoke.rs` has been moved into the crate as `src/tests.rs`.
=> Make `Stream::state` private to the crate.

Cargo.toml, src/frame/io.rs
Currently we always error when reading 0 bytes, however the correct thing to do is to signal the end of the stream iff there are no unparsed bytes in our buffer.
=> Fix EOF handling in `Io::poll_next`.

src/lib.rs, src/tests.rs
A leftover from https://github.com/paritytech/yamux/pull/62.
=> Do not export `stream::State`.

Cargo.toml, benches/concurrent.rs, src/connection/stream.rs, src/frame/io.rs, src/tests.rs, tests/concurrent.rs
Some notable changes:
- `BytesMut::bytes_mut` now returns a `&mut [MaybeUninit<u8>]` as it may contain uninitialised memory. Since we resize our buffer, which implies initialisation, we can just cast this slice to a `&mut [u8]` and use it directly.
- `BytesMut::remaining_mut` no longer gives the length of the `BytesMut::bytes_mut` as the `BufMut` implementation grows the buffer as needed. So, to figure out if we need to reserve another BLOCKSIZE chunk we now check how much capacity is left.
- `futures_codec` has been removed from tests as it has not updated to bytes-0.5. The tests now work directly with the stream as `AsyncRead` and `AsyncWrite` impl.
=> Update to bytes-0.5

src/frame/io.rs
Instead of reading large bodies in `BLOCKSIZE` steps, ensure that the buffer is large enough to hold the whole body which may result in less `poll_read` calls.
=> Allocate the whole frame body at once.

benches/concurrent.rs, src/connection.rs, src/connection/stream.rs, src/lib.rs, src/tests.rs
The impl produces `Packet`s which are simply newtype wrappers around `Bytes` and expose only an `AsRef<[u8]>` interface. The `futures::stream::Stream` implementation is more efficient than the
`AsyncRead` one as it does not need to copy the bytes.
=> Add `futures::stream::Stream` impl for `Stream`.

src/connection.rs, src/error.rs
When encountering an I/O error with `ErrorKind::ConnectionReset`, map this to a `ConnectionError::Closed` value. The remote may have closed the connection and a host implementing a "half-duplex" close sequence would send us a RST when we send data because we have not noticed the close yet. By mapping this case to a `ConnectionError::Closed` error, we effectively treat this case like any other connection close.
=> Map connection resets to `ConnectionError::Closed`.

src/connection.rs, src/connection/stream.rs, src/frame.rs, src/frame/header.rs, src/lib.rs
This PR changes two aspects related to newly opened inbound and outbound streams:
1. Up to now we never replied to opened inbound streams with an `ACK` flag, despite the fact that the spec clearly demands this behaviour. While we continue to ignore any `ACK` flags we receive, with this change we properly set an `ACK` flag if required.
2. The current behaviour is to always immediately send a `WindowUpdate` frame to the remote when opening an outbound stream. While we do not wait for an acknowledgement before we continue to send data over the stream, we could also hold off and set the initial `SYN` flag in the first data frame that is being sent over the new stream to the remote. The newly added option `lazy_open` enables this. This should eventually become the new default.
Additionally, …
=> Send `ACK`s and enable deferred `SYN`s.

Cargo.toml, benches/concurrent.rs, src/chunks.rs, src/connection.rs, src/connection/stream.rs, src/frame.rs, src/frame/io.rs, src/lib.rs, tests/concurrent.rs
The motivation for this change is the worry, that streams which do not consume their buffers in a timely manner prevent `BytesMut` from reusing their storage space, instead forcing it to allocate more memory.
This PR removes `bytes` completely and instead uses `Vec<u8>`s. The reclamation of storage is left to the allocator. As a side effect, all instances of `unsafe` are removed, so if merged, #66 can be considered done.
While at it we also remove the `BufWriter` from `Io`. Client code often already uses buffers and always adding another buffer layer seems misguided. If desired clients may always provide `Connection::new` with a `BufWriter` type.
=> Remove `bytes` dependency.

Cargo.toml, src/error.rs, src/frame/header.rs, src/frame/io.rs
Also disable default features for futures dependency so we do not always depend on proc-macros crates.
=> Remove `thiserror` dependency.

src/chunks.rs, src/connection.rs, src/connection/stream.rs
If `WindowUpdateMode` is `OnRead` and a stream is in state `SendClosed` when being dropped, we consider its buffer to determine if the remote may be blocked and needs to receive a reset frame. This is a bit odd as we could and should rather look at the stream's actual window size. If it is 0 we know that the remote may be blocked and since the stream is dropped no further window updates are forthcoming from our side, hence a RST frame should be sent right away. If it is > 0 the remote either has credit left or if it has not then the socket buffer must contain more data and we will answer with a RST for any unknown stream, so no action is necessary.
So why are we not looking at `window`? The reason is that we currently update the window before the window update is enqueued and if …
=> Reset dropped stream if window == 0.

src/connection.rs, src/tests.rs
PR #73 introduced a lazy open option to defer sending the initial frame when actual data is sent. If enabled and the initial data size equals DEFAULT_CREDIT (i.e. 256 KiB), it is necessary to immediately send a window update back when accepting such a stream, but only if window update mode is `OnReceive`, otherwise the update will be sent when the stream data is consumed.
With more options there are more ways how things can influence each other, so I have changed some tests to work with randomly generated configurations to test more combinations.
=> Send window update for initial data.

src/connection.rs, src/tests.rs
The current implementation always uses the configured receive window for the remote. However, when not sending the initial window update, this means that the remote stops sending before having used up its credit which it assumes matches the default receive window as it has not received an initial window update. Therefore, if `lazy_open` is true, the default receive window must be used initially.
=> If `lazy_open` use the default receive window.

src/tests.rs
* src/tests: Write and read concurrently
Most of the tests in `src/tests.rs` have the structure of a client
sending data to a server which in turn echoes the data back to the
client which reads it in full and compares it to what it initially sent.
Some of the tests use randomly generated configurations where the
`WindowUpdateMode` can be either `OnRead` or `OnReceive`. When using
`WindowUpdateMode::OnRead` the client can not first send a whole message to
the server and only then receive the whole message from the server. Say that
a single message exceeds the window between server and client. In such case
the server would eventually exhaust its window to the client, thus not being
able to forward bytes to the client, thus not accepting new bytes from the
client, thus the client would be …
=> src/tests: Write and read concurrently

Cargo.toml, benches/concurrent.rs
Previously the benchmarks would use an unbounded channel to simulate a
network connection. While this is helpful to measure the CPU impact of
Yamux specific changes, it is difficult to estimate how changes might
effect network throughput in different environments.
The crate [`constrained-connection`](https://github.com/mxinden/constrained-connection) can help simulate different
environments (DSL, HSDPA, GBit LAN, ...) by providing a channel
enforcing a specified bandwidth and delay. That said, it does not
simulate the OS network stack, routers, buffers, packet loss, ... Thus
as one would expect this can be used to detect trends, but not to e.g.
determine bandwidth expectations.
This commit makes the benchmarks run on top of a subset of the
connection types provided by …
=> benches: Benchmark with constrained connections 

.github/dependabot.yml
In my eyes Dependabot has been very helpful for rust-libp2p keeping its dependencies up-to-date. Thus I am suggesting to enable it for this repository as well. What do people think?
=> .github: Add dependabot

Cargo.toml, benches/concurrent.rs, src/tests.rs, tests/concurrent.rs
See https://github.com/paritytech/yamux/pull/102 for the preceding discussion. This PR adds a test that provokes a deadlock between two endpoints both wanting to write but cannot (i.e. `Pending`), though each could allow the other to make progress by reading. The test is disabled for now, due to actually stalling. It can be run with
```
RUST_LOG=yamux=debug cargo test deadlock -- --ignored
```
The logs will end with (`S` is the "server" echoing what the client sends, `C` is the "client" sending data it expects to get back, the "channel" is the artificially bounded "network connection")
```
[2021-02-04T15:13:35Z DEBUG yamux::tests::bounded] S: write: channel full, registering waker
...
[2021-02-04T15:13:35Z DEBUG yamux::tests::bounded] C: write: channel full, registering waker
```
i.e. …
=> [tests] Add a test for a potential write deadlock.

benches/concurrent.rs, src/chunks.rs, src/connection.rs, src/connection/stream.rs
To prevent senders from being blocked every time they have sent
RECEIVE_WINDOW (e.g. 256 KB) number of bytes, waiting for a WindowUpdate
message granting further sending credit, this commit makes Yamux send a
WindowUpdate message once half or more of the window has been received
(and consumed in `WindowUpdateMode::OnRead`). Benchmarking shows that
sending WindowUpdate messages early prevents senders from being blocked
waiting for additional credit on common network types.
For a detailed discussion as well as various benchmark results see
https://github.com/paritytech/yamux/issues/100.
Next to the above, this commit includes the following changes:
- Use `WindowUpdateMode::OnRead` in benchmarks. I would argue that
`OnRead` should be the default setting, given the importance of
flow-control. …
=> src/connection: Send WindowUpdate message early

src/connection/stream.rs, src/lib.rs
By limitting the data frame payload size one gains the following
beneftis:
1. Reduce delays sending time-sensitive frames, e.g. window updates.
2. Minimize head-of-line blocking across streams.
3. Enable better interleaving of send and receive operations, as each is
carried out atomically instead of concurrently with its respective
counterpart.
Limiting the frame size to 16KiB does not introduce a large overhead. A
Yamux frame header is 12 bytes large, thus this change introduces an
overhead of ~0.07%.
See https://github.com/paritytech/yamux/issues/100#issuecomment-774461550 and comments below that for details.
Might reduce probability for https://github.com/paritytech/yamux/pull/104 to happen.
=> src: Limit data frame payload size

CHANGELOG.md, Cargo.toml
This PR prepares the release of `v0.9`. A merge of this PR to `develop` will be followed up with a merge of `develop` into `master` for the release.
=> Prepare v0.9

Cargo.toml, src/connection.rs, src/frame.rs, src/frame/header.rs, src/frame/io.rs, src/tests.rs, tests/concurrent.rs
Currently, all write operations (e.g. for a particular frame sent by a substream) are `.await`ed for completion within the `Connection::next()` loop, thus prohibiting reading from the underlying socket while the write is pending. This can lead to unexpected write deadlocks between two peers in specific, though likely uncommon, situations. See  https://github.com/paritytech/yamux/pull/104 for further details and a test.
This PR proposes to allow concurrent reads while a frame write is pending, thereby propagating pending write back-pressure via the paused command channels, rather than doing so by "blocking"`Connection::next()` entirely until such a write completes.
Notably, no new buffers are introduced. We still send one frame at a time from the context of a `Connection`. However, when a …
=> Allow reads concurrent to pending writes.

CHANGELOG.md, Cargo.toml, src/lib.rs
Default to `WindowUpdateMode::OnRead`, thus enabling full Yamux
flow-control, exercising back pressure on senders, preventing stream
resets due to reaching the buffer limit.
See the [`WindowUpdateMode` documentation] for details, especially the
section on deadlocking when sending data larger than the receivers
window.
[`WindowUpdateMode` documentation]: https://docs.rs/yamux/0.9.0/yamux/enum.WindowUpdateMode.html
This would prevent surprises like https://github.com/libp2p/rust-libp2p/issues/2089.
=> src/lib: Default to WindowUpdateMode::OnRead

CHANGELOG.md
Not a large release, only https://github.com/libp2p/rust-yamux/pull/120.
Let me know in case anything else should be included.
=> CHANGELOG: Prepare v0.10.0

CHANGELOG.md, src/connection.rs
See the full conversation here: https://github.com/libp2p/rust-libp2p/issues/2461
The bump to Yamux 0.10 in libp2p broke the wasm-ext transport (used for WebSocket transport in WebAssembly). It turns out that the wasm-ext implementation makes it more prone to yield a `Pending` on a `poll_next` (see [this](https://github.com/libp2p/rust-libp2p/blob/96dbfcd1ade6de5b4ae623f59fb0d67b2916576a/transports/wasm-ext/src/lib.rs#L485)). When used in conjunction with Noise, a frame may get buffered and only written to the underlying I/O stream when flushing it (see [this](https://github.com/libp2p/rust-libp2p/blob/b79fd02f0bdde07f437c691e278a16cf9024036a/transports/noise/src/io.rs#L138)) 
In https://github.com/libp2p/rust-yamux/pull/112, flushing is no longer awaited, but instead, is called at each …
=> Fix connection flush

CHANGELOG.md, Cargo.toml, src/connection.rs
> The `frame` future might be _ready_ with an `Error` from the underlying
socket (i.e. here `libp2p-websocket`). Though given that the result of the
`control_command` `Future` is handled first, `on_control_command` is called
despite `frame` having returned an `Error`. `on_control_command` itself may try
to write to the underlying socket, which will panic given that the socket
returned an error earlier via the `frame` `Future`.
With this patch, once any of `next_stream_command`, `next_control_command` or
`next_frame` `Future` is ready, the result is processed right away, without
additionally polling the remaining pending `Future`s, thus surfacing errors as
early as possible.
See https://github.com/libp2p/rust-libp2p/issues/2598 for details.
@elenaf9 @thomaseizinger could either of you do …
=> src/connection: Process command or socket result immediately

src/connection/stream.rs, src/lib.rs, tests/concurrent.rs, tests/tests.rs
As part of #142, I had a look at the tests and I found them rather hard to understand.
This PR attempts to improve this situation. It is a clean refactoring, no behaviour has been changed and should thus hopefully be non-controversial.
=> Refactor tests

yamux/Cargo.toml
Release fails with the below otherwise:
```
error: failed to read `readme` file for package `yamux v0.11.0 (/home/xxx/rust-yamux/yamux)`
```
=> fix: Remove dead link to README.md

CHANGELOG.md, yamux/Cargo.toml
@thomaseizinger with https://github.com/libp2p/rust-yamux/pull/156 merged, what do you think of a new release?
This will allow us to proceed with https://github.com/libp2p/rust-libp2p/pull/3013. We can merge and release https://github.com/libp2p/rust-yamux/pull/153 as a patch release and https://github.com/libp2p/rust-yamux/issues/154 with the next breaking release.
=> chore: prepare v0.11.1

test-harness/src/lib.rs, test-harness/tests/poll_api.rs, test-harness/tests/tests.rs
Whilst debugging some test failures for #156, I rewrote one more test to use the poll-based interface.
Related: #157.
=> refactor: move more tests to poll-API based interface

CHANGELOG.md
I suggest we release `v0.12.0` right away. Most important change is https://github.com/libp2p/rust-yamux/pull/167.
@thomaseizinger any objections?
@aschran is that good enough for you, or would you need a `v0.11.2` patch release?
=> chore: prepare v0.12.0

yamux/src/connection.rs, yamux/src/connection/stream.rs, yamux/src/lib.rs
`Control` and `Connection::next_stream` has been removed since 0.11 and 0.12, in favor of poll-based methods on `Connection`.
The PR updated doc comments regarding those structs. Some outdated non-doc comments at the top of connection.rs (L12) are unchanged, because I am not familiar with the crate enough to rewrite that part.
This fixes #171.
=> docs: remove mentions of old API components

CHANGELOG.md, yamux/Cargo.toml, yamux/src/connection.rs, yamux/src/connection/stream.rs, yamux/src/lib.rs
Continuation of https://github.com/libp2p/rust-yamux/pull/120.
Preparation for https://github.com/libp2p/rust-yamux/issues/175.
Also removes dead-lock warning for `WindowUpdateMode::OnRead`. With the restructuring of `Connection::poll`, one reads from the socket when writing is blocked. Thus the deadlock can not occur.
=> chore: deprecate `WindowUpdateMode::OnReceive`

Cargo.toml, test-harness/Cargo.toml, yamux/Cargo.toml
If I understand correctly, this is a local change only, and thus does not require a changelog entry. Am I correct @thomaseizinger? Any objections?
=> chore: move to Rust edition 2021

CHANGELOG.md, test-harness/benches/concurrent.rs, test-harness/src/lib.rs, yamux/Cargo.toml, yamux/src/connection.rs, yamux/src/connection/stream.rs, yamux/src/lib.rs
Follow up to previous deprecation https://github.com/libp2p/rust-yamux/pull/177.
Fixes https://github.com/libp2p/rust-yamux/issues/175.
=> chore: remove `WindowUpdateMode::OnReceive`

CHANGELOG.md, yamux/Cargo.toml, yamux/src/connection/rtt.rs, yamux/src/connection/stream/flow_control.rs
See https://github.com/sebcrozet/instant/issues/52 and https://github.com/libp2p/rust-libp2p/pull/5347.
=> feat: Use `web-time` instead of `instant`

yamux/src/connection.rs
Readers should be woken up after setting the state to RecvClosed otherwise they potentially miss reading the EOF entirely.
Closes #189
=> fix: wake up readers after setting the state to RecvClosed

yamux/src/connection/closing.rs
When yamux connection is closing it should:
- Send pending frames.
- Send `GoAway` frame.
- Close underlying connection.
But test showed that pending frames from `stream_receivers` and `GoAway` frame were not sent.
Commits introducing this bug:
- https://github.com/libp2p/rust-yamux/commit/61003c53cec1b5b37f8c05231e44efea0077ad07 replaced `VecDeque` with `Option`,
which caused loss of pending frames,
because only last pending frame was stored in `Option`
- https://github.com/libp2p/rust-yamux/commit/297e9eba1f30ded3a2b4bb46c8bd8cf2fb4471db reordered sending and collecting pending frames,
trying to fix loss of pending frames.
- https://github.com/libp2p/rust-yamux/commit/286728026d8ec15cb4120028d3fabdbd35ebf3ca reverted https://github.com/libp2p/rust-yamux/commit/61003c53cec1b5b37f8c05231e4 …
=> Fix closing pending frames

CHANGELOG.md, yamux/Cargo.toml, yamux/src/connection.rs
The connection state can become `Poisoned` if poll_close returns an error. Although an implementer should never poll again after an error, the connection state should also never be `Poisoned` (`unreachable!`).
=> fix: avoid possible poisoned connection when closing
